### ISSUE TITLE
expand table height

### ISSUE THREAD

**Issue by andrewsu** [SuLab/Lit2Hybrid#3]
Currently, table only can display 4 rows before a slider bar cuts output. 
![image](https://user-images.githubusercontent.com/2635409/81584423-96d9eb80-9367-11ea-8dd3-e61a1df9cf5f.png)

A better solution would be to just let the table go as tall as it needs to be, and let the parent window create a slider bar as necessary.

The _best_ solution would be the solution above, *plus* having the header row be "sticky" as the user scrolls down.

**Comment by rampeace** [comment]
I created sticky header and column. The table will create vertical and horizontal bars when required. The table colours / hovers or the entire design may be changed. Please let me know about the changes required.

**Comment by andrewsu** [comment]
The sticky header seems to work, but I see a double vertical scroll bar:

![image](https://user-images.githubusercontent.com/2635409/82236767-71119100-98e9-11ea-8fce-41fdbd467d13.png)

Would be best to eliminate that.  Seems like a CSS issue -- if that's not your strength, no problem.  Let me know and I can have our front-end developer look at it.

I think mobile compatibility would be nice to have, but the vast majority of users will be accessing from a laptop or desktop I think...

**Comment by rampeace** [comment]
When moved vertically the form will sometimes jumps a little. I'm still finding better solution to it.

**Comment by rampeace** [comment]
#11 I modified the css to fix the small jumping problem. I think this issue can be closed now.
