### ISSUE TITLE
remove (or document) counter?

### ISSUE THREAD

**Issue by andrewsu** [SuLab/Lit2Hybrid#4]
It looks like there is a counter under the first text box:

![image](https://user-images.githubusercontent.com/2635409/81585657-51b6b900-9369-11ea-984e-a25ac45a600a.png)

Was that for debugging purposes and therefore can be removed, or is it meaningful (and hence should be documented)?

**Comment by rampeace** [comment]
I left this for debugging purposes. No it's not required. I have removed in the current push.
