### ISSUE TITLE
Allow a user to (optionally) enter an eUtils API key that will allow faster query frequency

### ISSUE THREAD

**Issue by andrewsu** [SuLab/Lit2Hybrid#5]
These API keys would *only* be stored locally in the user's browser. Ideally, should be persistent across sessions.

**Comment by rampeace** [comment]
I'm currently working on this feature.

**Comment by rampeace** [comment]
I have few doubts.
1) We may persist api key during page reloads but let it go away once the tab or browser window is closed. In the second way, we can persist even after the window is closed. The second way might be suitable if the user is on his own machine. Perhaps we can make the first method as default and provide an optional check box "save to this computer" which then switch to the second method.

2) If the user provides a wrong api key, the server is responding with error. "Invalid api key".  In the present implementation, for any error, it will skip and proceed to the next request to try. This might be okay if the error is network down, which we can expect it to be back sometime. But in case of wrong API key, we probably want to stop all the future requests? May be giving an error message to the user?

**Comment by andrewsu** [comment]
Great points!

1) This sounds like a good plan to me.  And just to be sure I understand what you're thinking on a technical level, are you going to use `sessionStorage` and `localStorage` for temporary and persistent storage, respectively?

2) Yes, that seems like a good behavior -- an "invalid API key" error would cause all subsequent API calls to be canceled.  In addition, it might be good to do a quick validation of the API key right when the user saves it. And, for the case that an API key becomes invalid after that initial validation, you would need to provide a mechanism for the user to delete a locally-stored API key.

**Comment by rampeace** [comment]
>     1. are you going to use `sessionStorage` and `localStorage` for temporary and persistent storage, respectively?

Yes. `localStorage` for user's who saved the key. `sessionStorage` for other users. 
>     2\. And, for the case that an API key becomes invalid after that initial validation, you would need to provide a mechanism for the user to delete a locally-stored API key.
I think a toggle button like this might work. Key can be stored or removed based on toggle.
![image](https://user-images.githubusercontent.com/15014898/82325081-42361080-99f8-11ea-91d3-a3c5a917f044.png)

If api key is already stored on the machine, it will show up by default on page load, along with toggle on. The other options to have a button to add/delete the key with alert message are there as well.

**Comment by andrewsu** [comment]
on point 2 above, that interface makes sense. So if a user enters an API key with the "Remember" toggle in the "on" state, then when that user hits "Search", that key gets written to localStorage?  And if they subsequently clear the API key field and hit search, then that info is cleared from localStorage?

**Comment by rampeace** [comment]
Yes. correct.

**Comment by rampeace** [comment]
We could possibly create a dev branch before we merge to master.
Some key points I would like to share about this feature.
1) API key will validate before to proceed and gives an error  message if it's invalid.
2) API key can _also_ be added in the middle of a search. In this case the search won't restart.
3) If term or modifier is changed in the middle of a search, internally the ongoing async operation will be cancelled and then search will restart
4) The app will continue to work without any page reload.

**Comment by rampeace** [comment]
#11 I have modified the css for improved performance. The small jumping won't happen again.  I think this can be closed now.
