### ISSUE TITLE
eliminate "batches" of eutils requests in favor of consistent delay

### ISSUE THREAD

**Issue by andrewsu** [SuLab/Lit2Hybrid#6]
Currently, eutils requests seem to be executed in batches of 3:

![image](https://user-images.githubusercontent.com/2635409/81586094-e91c0c00-9369-11ea-9d4d-1558ffd5736f.png)

Would be better to simply have a constant 1/3 second gap between each request.  This may be even more important when we allow higher rates with an API key (#5) because in another project, it appears that eutils will quickly block if many requests are sent in rapid succession.  In other words, a batch of 10 requests followed by a one second pause gets blocked, whereas a 0.1 second pause between requests is fine.

**Comment by rampeace** [comment]
Yes. presently the requests are executed in batches of 3. Slicing the 1 second for each request makes lot of sense.

**Comment by rampeace** [comment]
I fixed this by sending requests at 1/3 second. All requests are succeeding now. The fix has been checked in. I am yet to implement api key.
