### ISSUE TITLE
allow editing of query matrix

### ISSUE THREAD

**Issue by andrewsu** [SuLab/Lit2Hybrid#7]
clearly not an MVP feature, but it would be nice to allow users to add new columns and rows without having to re-execute the entire matrix.  For example, one possible interface:

![image](https://user-images.githubusercontent.com/2635409/81588053-c63f2700-936c-11ea-873c-f034c69eae09.png)

**Comment by rampeace** [comment]
Now that sticky rows and columns added, the rows and columns can extend vertically and horizontally.  Are we still okay with this design

**Comment by andrewsu** [comment]
Yes, I _think_ the design described in the mockup above would still work well, but let me know if you see issues that I might be missing...

**Comment by andrewsu** [comment]
on thinking more, it would be cool if clicking either "add a term" button in the mockup above raised a modal dialog box.  Users could then easily paste in a list of new query terms.  Clicking "submit" would then prompt the app to queue the new queries for execution.  An example mockup of the modal dialog is below:

![image](https://user-images.githubusercontent.com/2635409/83305376-7c03d580-a1b5-11ea-9c9d-3833b6354487.png)

**Comment by rampeace** [comment]
Thank you for the design. We shall proceed with this.

**Comment by rampeace** [comment]
d884247a3850e37a72c357ec7ba8318b3bfa5af9 

Please refer this commit for changes related to this feature.

**Comment by rampeace** [comment]
This feature was working fine. So I'm closing this now.
